name: Run Jmeter Tests from Config File
on:
  push:
    branches:
      - main
  
jobs:  
  api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [folder-1, folder-3]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "./scripts/${{ matrix.folder }}/script.sh" ]; then
            bash "./scripts/${{ matrix.folder }}/script.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  ui:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        folder: [folder-2]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "./scripts/${{ matrix.folder }}/script.sh" ]; then
            bash "./scripts/${{ matrix.folder }}/script.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  api-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [folder-1, folder-3]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "./scripts/${{ matrix.folder }}/script.sh" ]; then
            bash "./scripts/${{ matrix.folder }}/script.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
