name: Run Jmeter Tests from Config File
on:
  push:
    branches:
      - main

jobs:
  job1-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [a2000***us-east-1*** DeterAPI -scr1,scr2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "./scripts/${{ matrix.folder }}/script.sh" ]; then
            bash "./scripts/${{ matrix.folder }}/script.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job2-ui:
    runs-on: windows-latest
    needs: job1-api
    strategy:
      matrix:
        folder: [a2000***us-east-1*** Deter- scr1,scr2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "./scripts/${{ matrix.folder }}/script.sh" ]; then
            bash "./scripts/${{ matrix.folder }}/script.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job3-api:
    runs-on: ubuntu-latest
    needs: job2-ui
    strategy:
      matrix:
        folder: [a2000***us-east-1*** DeterAPI -scr1,scr2,scr3,scr4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "./scripts/${{ matrix.folder }}/script.sh" ]; then
            bash "./scripts/${{ matrix.folder }}/script.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
