name: Run Jmeter Tests from Config File

on:
  push:
    branches:
      - main
    paths:
      - Triggers/workflow_jmx.txt

  workflow_dispatch:
    inputs:
      job_name:
        description: 'name of the job to run(optional)'
        required: false
        default: ''
jobs:
  api:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'

            - name: Install Dependencies
              run: pip install pyyaml

            - name: Parse config and run scripts
              run: |
                python3 .github/scripts/run_from_config.py
              env:
                FOLDER: API
                

  ui:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'

            - name: Install Dependencies
              run: pip install pyyaml

            - name: Parse config and run scripts
              run: |
                python3 .github/scripts/run_from_config.py
              env:
                FOLDER: UI
